/* Generated by Frama-C */
void __VERIFIER_assert_slice_1(void)
{
  return;
}

void main(void)
{
  unsigned int x = (unsigned int)0;
  while (x < (unsigned int)0x0fffffff) x ++;
  __VERIFIER_assert_slice_1();
  return;
}


