/* Generated by Frama-C */
void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}


void __VERIFIER_assert_slice_1(void)
{
  reach_error_slice_1();
  return;
}

unsigned int f_slice_1(unsigned int z)
{
  unsigned int __retres;
  __retres = z + (unsigned int)2;
  return __retres;
}

void main(void)
{
  unsigned int x = (unsigned int)0;
  while (x < (unsigned int)0x0fffffff) x = f_slice_1(x);
  __VERIFIER_assert_slice_1();
  return;
}


