/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

void main(void)
{
  unsigned int x = (unsigned int)0;
  unsigned int y = (unsigned int)10000000;
  unsigned int z = (unsigned int)5000000;
  while (x < y) {
    if (x >= (unsigned int)5000000) z --;
    x ++;
  }
  __VERIFIER_assert_slice_1(z != (unsigned int)0);
  return;
}
