/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(void)
{
  reach_error_slice_1();
  return;
}

void main(void)
{
  __VERIFIER_assert_slice_1();
  return;
}