/* Generated by Frama-C */
void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}


void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

/*@ assigns \result;
    assigns \result \from \nothing; */
extern unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  int i;
  unsigned int tmp;
  int tmp_0;
  tmp = __VERIFIER_nondet_uint();
  int n = (int)tmp;
  int sn = 0;
  i = 1;
  while (i <= n) {
    if (i < 10) sn += 2;
    /*@ assert Eva: signed_overflow: i + 1 ≤ 2147483647; */
    i ++;
  }
  /*@ assert Eva: signed_overflow: -2147483648 ≤ n * 2; */
  /*@ assert Eva: signed_overflow: n * 2 ≤ 2147483647; */
  if (sn == n * 2) tmp_0 = 1;
  else
    if (sn == 0) tmp_0 = 1; else tmp_0 = 0;
  __VERIFIER_assert_slice_1(tmp_0);
  return;
}