/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
void main(void)
{
  int b = 20;
  return;
}


/* Generated by Frama-C */
#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
void main(void)
{
  int b = 20;
  return;
}


