/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
#include "string.h"
int main(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}


/* Generated by Frama-C */
int main(void)
{
  int __retres;
  __retres = 0;
  return __retres;
}


