/* Generated by Frama-C */
int main(void)
{
  int a;
  int c;
  int volatile b = 0;
  a = 1;
  c = 0;
  /*@ loop assigns c, a; */
  while (c <= 5) {
    a = 2;
    c ++;
  }
  if (b) goto L;
  a += 2;
  L: a += 3;
  goto H;
  H: ;
  return a;
}


/* Generated by Frama-C */
int main(void)
{
  int a;
  int c;
  int volatile b = 0;
  a = 1;
  c = 0;
  /*@ loop assigns c, a; */
  while (c <= 5) {
    a = 2;
    c ++;
  }
  if (b) goto L;
  a += 2;
  L: a += 3;
  goto H;
  H: ;
  return a;
}


