/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int mult_slice_1(int x, int y)
{
  int __retres;
  __retres = x * y;
  return __retres;
}

/*@ requires valid_read_string(format); */
int printf_va_1(char const * restrict format, int param0);

/*@ requires valid_read_string(format); */
int printf_va_2(char const * restrict format, int param0);

/*@ requires valid_read_string(format); */
int printf_va_3(char const * restrict format, int param0);

/*@ requires valid_read_string(format); */
int printf_va_4(char const * restrict format);

void main(void)
{
  int tmp;
  int x = 0;
  int y = 1;
  int z = 2;
  printf_va_1("x: %d\n",x);
  printf_va_2("y: %d\n",y);
  printf_va_3("z: %d\n",z);
  tmp = mult_slice_1(x,y);
  printf_va_4((char const *)tmp);
  return;
}


/* Generated by Frama-C */
#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
int mult_slice_1(int x, int y)
{
  int __retres;
  __retres = x * y;
  return __retres;
}

/*@ requires valid_read_string(format); */
int printf_va_1(char const * restrict format, int param0);

/*@ requires valid_read_string(format); */
int printf_va_2(char const * restrict format, int param0);

/*@ requires valid_read_string(format); */
int printf_va_3(char const * restrict format, int param0);

/*@ requires valid_read_string(format); */
int printf_va_4(char const * restrict format);

void main(void)
{
  int tmp;
  int x = 0;
  int y = 1;
  int z = 2;
  printf_va_1("x: %d\n",x);
  printf_va_2("y: %d\n",y);
  printf_va_3("z: %d\n",z);
  tmp = mult_slice_1(x,y);
  printf_va_4((char const *)tmp);
  return;
}


