/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int foo_slice_1(int x)
{
  int __retres;
  __retres = x + 1;
  return __retres;
}

int main(void)
{
  int __retres;
  int a = 10;
  int c = foo_slice_1(a);
  __retres = 0;
  return __retres;
}


/* Generated by Frama-C */
#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
int foo_slice_1(int x)
{
  int __retres;
  __retres = x + 1;
  return __retres;
}

int main(void)
{
  int __retres;
  int a = 10;
  int c = foo_slice_1(a);
  __retres = 0;
  return __retres;
}


