/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int foo_slice_1(int x)
{
  int __retres;
  __retres = x + 1;
  return __retres;
}

void main(void)
{
  int a = 10;
  int c = foo_slice_1(a);
  return;
}


/* Generated by Frama-C */
#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
int foo_slice_1(int x)
{
  int __retres;
  __retres = x + 1;
  return __retres;
}

void main(void)
{
  int a = 10;
  int c = foo_slice_1(a);
  return;
}


