/* Generated by Frama-C */
void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}


void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

void main(void)
{
  unsigned int x = (unsigned int)0;
  unsigned int y = (unsigned int)0;
  while (x < (unsigned int)1000000) {
    if (x < (unsigned int)500000) y ++; else y --;
    x ++;
  }
  __VERIFIER_assert_slice_1(y != (unsigned int)0);
  return;
}