/* Generated by Frama-C */
#include "errno.h"
#include "math.h"
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

float pi = (float)3.14159;
/*@ assigns \result;
    assigns \result \from \nothing; */
extern int __VERIFIER_nondet_int(void);

double diff_slice_1(double x1, double x2)
{
  double __retres;
  if (x1 > x2) __retres = x1 - x2; else __retres = x2 - x1;
  return __retres;
}

double radianMeasure_slice_1(int degrees)
{
  double __retres;
  __retres = (double)((float)degrees * (pi / (float)180));
  return __retres;
}

void main(void)
{
  int x;
  float angleInRadian;
  int temp;
  double tmp_3;
  float phaseLag = pi / (float)2;
  float phaseLead = pi;
  double sum1 = 0.0;
  double sum2 = 0.0;
  double count = 0.0;
  while (1) {
    {
      double tmp_0;
      double tmp_1;
      double tmp_2;
      x = __VERIFIER_nondet_int();
      tmp_0 = radianMeasure_slice_1(x);
      angleInRadian = (float)tmp_0;
      tmp_1 = sin((double)(angleInRadian + (float)2 * phaseLead));
      sum2 += tmp_1;
      tmp_2 = cos((double)(angleInRadian + phaseLag));
      sum1 += tmp_2;
      temp = __VERIFIER_nondet_int();
      count += (double)1;
      if (temp == 0) break;
    }
  }
  tmp_3 = diff_slice_1(sum1,sum2);
  __VERIFIER_assert_slice_1(tmp_3 <= count);
  return;
}