/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

/*@ assigns \result;
    assigns \result \from \nothing; */
int __VERIFIER_nondet_int(void);

void main(void)
{
  int idBitLength;
  int material_length;
  int nlen;
  int j;
  nlen = __VERIFIER_nondet_int();
  idBitLength = __VERIFIER_nondet_int();
  material_length = __VERIFIER_nondet_int();
  if (! (nlen == idBitLength / 32)) goto return_label;
  j = 0;
  while (1) {
    if (j < idBitLength / 8) {
      if (! (j < material_length)) break;
    }
    else break;
    __VERIFIER_assert_slice_1(0 <= j);
    __VERIFIER_assert_slice_1(j < material_length);
    __VERIFIER_assert_slice_1(0 <= j / 4);
    __VERIFIER_assert_slice_1(j / 4 < nlen);
    j ++;
  }
  return_label: return;
}
