/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

/*@ assigns \result;
    assigns \result \from \nothing; */
extern unsigned char __VERIFIER_nondet_uchar(void);

void main(void)
{
  unsigned char n = __VERIFIER_nondet_uchar();
  if ((int)n == 0) goto return_label;
  unsigned char v = (unsigned char)0;
  unsigned char s = (unsigned char)0;
  unsigned int i = (unsigned int)0;
  while (i < (unsigned int)n) {
    v = __VERIFIER_nondet_uchar();
    s = (unsigned char)((int)s + (int)v);
    i ++;
  }
  if ((int)s < (int)v) reach_error_slice_1();
  return_label: return;
}