/* Generated by Frama-C */
void __VERIFIER_assert_slice_1(void)
{
  return;
}

void main(void)
{
  unsigned int x = (unsigned int)10;
  while (x >= (unsigned int)10) x += (unsigned int)2;
  __VERIFIER_assert_slice_1();
  return;
}


