/* Generated by Frama-C */
extern int __VERIFIER_nondet_int(void);

void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}

void __VERIFIER_assert_slice_1(void)
{
  return;
}

void main(void)
{
  int A[1024];
  int i;
  i = 0;
  while (i < 1024) {
    A[i] = __VERIFIER_nondet_int();
    i ++;
  }
  i = 0;
  while (A[i] != 0) i ++;
  __VERIFIER_assert_slice_1();
  return;
}


