/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int add_slice_1(int a, int b)
{
  /*@ slice pragma expr "add"; */ ;
  int result = a + b;
  return result;
}

int multiply_slice_1(int a, int b)
{
  /*@ slice pragma expr "multiply"; */ ;
  int result = a * b;
  return result;
}

void main(void)
{
  int x = 5;
  int y = 10;
  int sum = add_slice_1(x,y);
  int product = multiply_slice_1(x,y);
  /*@ assert y ≥ x; */ ;
  /*@ assert sum ≡ x + y; */ ;
  return;
}


