/* Generated by Frama-C */
void __VERIFIER_assert_slice_1(void)
{
  return;
}

unsigned int f_slice_1(unsigned int z)
{
  unsigned int __retres;
  __retres = z + (unsigned int)2;
  return __retres;
}

int main(void)
{
  int __retres;
  unsigned int x = (unsigned int)0;
  while (x < (unsigned int)0x0fffffff) x = f_slice_1(x);
  __VERIFIER_assert_slice_1();
  __retres = 0;
  return __retres;
}


