/* Generated by Frama-C */
void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}


void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

/*@ assigns \result;
    assigns \result \from \nothing; */
unsigned int __VERIFIER_nondet_uint(void);

void main(void)
{
  unsigned int array[10000];
  unsigned int index;
  int tmp_0;
  unsigned int tmp = (unsigned int)0;
  while (1) {
    index = __VERIFIER_nondet_uint();
    if (index >= (unsigned int)10000) break;
    array[index] = index;
    tmp = index;
  }
  /*@ assert Eva: initialization: \initialized(&array[tmp]); */
  if (array[tmp] == tmp) tmp_0 = 1; else tmp_0 = 0;
  __VERIFIER_assert_slice_1(tmp_0);
  return;
}