/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
void reach_error_slice_1(void)
{
  return;
}

extern int __VERIFIER_nondet_int(void);

void __VERIFIER_assert_slice_1(int cond)
{
  /*@ slice pragma stmt; */
  if (! cond) reach_error_slice_1();
  return;
}

void main(void)
{
  int A[2048];
  int B[2048];
  int i;
  int tmp;
  i = 0;
  while (i < 2048) {
    A[i] = __VERIFIER_nondet_int();
    B[i] = __VERIFIER_nondet_int();
    i ++;
  }
  i = 0;
  while (i < 2048) {
    tmp = A[i];
    B[i] = tmp;
    i ++;
  }
  __VERIFIER_assert_slice_1(A[2048 / 2] == B[2048 / 2]);
  return;
}


