/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

/*@ assigns \result;
    assigns \result \from \nothing; */
int __VERIFIER_nondet_int(void);

void main(void)
{
  int x;
  int y;
  int z;
  int w;
  int tmp_2;
  w = 0;
  z = w;
  y = z;
  x = y;
  while (1) {
    int tmp_1;
    tmp_1 = __VERIFIER_nondet_int();
    if (tmp_1) {
      if (! (y < 10000)) break;
    }
    else break;
    {
      int tmp_0;
      tmp_0 = __VERIFIER_nondet_int();
      if (tmp_0) {
        /*@ assert Eva: signed_overflow: x + 1 ≤ 2147483647; */
        x ++;
        y += 100;
      }
      else {
        int tmp;
        tmp = __VERIFIER_nondet_int();
        if (tmp) {
          if (x >= 4) {
            /*@ assert Eva: signed_overflow: x + 1 ≤ 2147483647; */
            x ++;
            y ++;
          }
        }
        else
          /*@ assert Eva: signed_overflow: 10 * w ≤ 2147483647; */
          if (y > 10 * w)
            /*@ assert Eva: signed_overflow: 100 * x ≤ 2147483647; */
            if (z >= 100 * x) y = - y;
      }
      /*@ assert Eva: signed_overflow: w + 1 ≤ 2147483647; */
      w ++;
      /*@ assert Eva: signed_overflow: z + 10 ≤ 2147483647; */
      z += 10;
    }
  }
  if (x >= 4)
    if (y <= 2) tmp_2 = 1; else tmp_2 = 0;
  else tmp_2 = 0;
  __VERIFIER_assert_slice_1(tmp_2);
  return;
}