/* Generated by Frama-C */
/*@ assigns \nothing; */
extern  __attribute__((__nothrow__, __noreturn__)) void __assert_fail
(char const *, char const *, unsigned int, char const *) __attribute__((
__leaf__));

void reach_error_slice_1(void)
{
  __assert_fail("0","nested_1-2.c",(unsigned int)3,"reach_error");
  return;
}

void __VERIFIER_assert_slice_1(void)
{
  reach_error_slice_1();
  return;
}

void main(void)
{
  unsigned int x = (unsigned int)0;
  unsigned int y = (unsigned int)0;
  while (x < (unsigned int)0x0fffffff) {
    y = (unsigned int)0;
    while (y < (unsigned int)10) y ++;
    x ++;
  }
  __VERIFIER_assert_slice_1();
  return;
}


