/* Generated by Frama-C */
void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}


void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

/*@ assigns \result;
    assigns \result \from \nothing; */
int __VERIFIER_nondet_int(void);

/*@ assigns \result;
    assigns \result \from size; */
 __attribute__((__FC_BUILTIN__)) void *__fc_vla_alloc(unsigned long size);

void main(void)
{
  unsigned int j;
  unsigned long __lengthof_array;
  int menor;
  unsigned int SIZE = (unsigned int)1;
  __lengthof_array = (unsigned long)SIZE;
  int *array = __fc_vla_alloc(sizeof(int) * __lengthof_array);
  menor = __VERIFIER_nondet_int();
  j = (unsigned int)0;
  while (j < SIZE) {
    *(array + j) = __VERIFIER_nondet_int();
    if (*(array + j) <= menor) menor = *(array + j);
    j ++;
  }
  __VERIFIER_assert_slice_1(*(array + 0) > menor);
  return;
}
