/* Generated by Frama-C */
/*@ assigns \nothing; */
extern  __attribute__((__nothrow__, __noreturn__)) void __assert_fail
(char const *, char const *, unsigned int, char const *) __attribute__((
__leaf__));

void reach_error() { assert(0); }

void reach_error_slice_1(void){
  ERROR: {reach_error();}
  return;
}


extern unsigned int __VERIFIER_nondet_uint(void);

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

void main(void)
{
  unsigned int x = __VERIFIER_nondet_uint();
  unsigned int y = x + (unsigned int)1;
  while (x < (unsigned int)1024) {
    x ++;
    y ++;
  }
  __VERIFIER_assert_slice_1(x == y);
  return;
}


