/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

void main(void)
{
  int x = 0;
  int y = 500000;
  while (x < 1000000)
    if (x < 500000) x ++;
    else {
      x ++;
      /*@ assert Eva: signed_overflow: y + 1 ≤ 2147483647; */
      y ++;
    }
  __VERIFIER_assert_slice_1(y != x);
  return;
}