/* Generated by Frama-C */
void reach_error_slice_1(void)
{
  return;
}

void __VERIFIER_assert_slice_1(int cond)
{
  if (! cond) reach_error_slice_1();
  return;
}

void main(void)
{
  unsigned int x = (unsigned int)0;
  while (x < (unsigned int)100000000)
    if (x < (unsigned int)10000000) x ++; else x += (unsigned int)2;
  __VERIFIER_assert_slice_1(x == (unsigned int)100000001);
  return;
}